### ISSUE TITLE
Move component meta extraction to unplugin

### ISSUE THREAD

**Issue by stafyniaksacha** [nuxtlabs/nuxt-component-meta#33]
It would be great to allow to extract components meta directly with builder, via `unbuild`.

So we can use the meta for different purpose, and expose it in different ways

**Comment by Tahul** [comment]
Hello :)

I will take care of that soon, that also is needed for #42

Also, one issue that could happen is that with current approach, parsing will only occur on the filesystem version of the component, which can differ from the one that is passed to `@vue/compiler-sfc`, if it is targeted by transforms.

That would lead to inconsistent result between what is rendered / what data is accessible via the module.
