### ISSUE TITLE
Issue with components from node_modules

### ISSUE THREAD

**Issue by farnabaz** [nuxtlabs/nuxt-component-meta#37]
It seems that vue-component-meta could not load components from node_modules.

Can be reproduced in [this branch](https://github.com/nuxtlabs/nuxt-component-meta/tree/external-components)

<img width="1010" alt="Screenshot 2022-08-29 at 13 53 58" src="https://user-images.githubusercontent.com/2047945/187195270-e4b8495d-4193-4f6b-867f-bde2719ffeba.png">

/cc @stafyniaksacha

**Comment by stafyniaksacha** [comment]
I think this comes from default `exclude` (or from `skipLibCheck`?) from tsconfig even if we've added:

```json
 "include": [
    "**/*"
 ]
```

I will check if we can have something clean

**Comment by stafyniaksacha** [comment]
In addition, we should have NuxtLink/NuxtLayout/NuxtPage/... components too

**Comment by farnabaz** [comment]
I think they are excluded from the hook, we should add them manually to the components list

**Comment by stafyniaksacha** [comment]
@farnabaz the example you provided is a bit tricky, `node_modules` is in upper scope of `nuxt.options.rootDir`, we may need a workspace to have correct tree, what do you think?

**Comment by farnabaz** [comment]
Do you think there is any way to resolve these files without creating a workspace? We have a similar structure in multiple packages, mainly for development environments and playgrounds.
Most likely nuxt-content-meta will be installed and used on lots of projects, forcing users to have a workspace may not bring good DX

**Comment by Atinux** [comment]
Agree with @farnabaz it should work whatever their project structure

**Comment by stafyniaksacha** [comment]
> Do you think there is any way to resolve these files without creating a workspace? 

Done in #38, let me know your feedback
