### ISSUE TITLE
Slot detection

### ISSUE THREAD

**Issue by farnabaz** [nuxtlabs/nuxt-component-meta#39]
Seems that [removing tsconfig](https://github.com/nuxtlabs/nuxt-component-meta/pull/38/files#diff-030fc083b2cbf5cf008cfc0c49bb4f1b8d97ac07f93a291d068d81b4d1416f70L50) broke slot detection.

**Comment by stafyniaksacha** [comment]
We can use 
```
extends: `${nuxt.options.rootDir}/tsconfig.json`,
```

but it may fail if it does not exist

**Comment by farnabaz** [comment]
Every nuxt project has `tsconfig` in their root dir, so I think it should be safe to add this.
