### ISSUE TITLE
extra quotes in string values

### ISSUE THREAD

**Issue by farnabaz** [nuxtlabs/nuxt-component-meta#41]
String values are wrapped in a single quote and this extra quote seems redundant.
Removing these extra quotes brings simplicity to the users.

```
{
        "name": "hello",
        "default": "'Hello'",
        ....
}
```

**Comment by Tahul** [comment]
@farnabaz is this still relevant?

**Comment by farnabaz** [comment]
I think it is still relevant, because Vue component meta doesn't remove these extra quotes

**Comment by Tahul** [comment]
👍, will take care of that

**Comment by Tahul** [comment]
@farnabaz ; I explored excluding extra quotes, but I'm afraid it will have to be done upstream.

I think extra quotes are actually "valid" in the sense that Vue Component Meta returns the whole content of props default.

I'm afraid that if we apply normalization for such values, we might have do to it in lots of places.

@Atinux ; do you think we should push for improvements upstream (`vue-component-meta` ?)?

**Comment by stafyniaksacha** [comment]
> I think extra quotes are actually "valid" in the sense that Vue Component Meta returns the whole content of props default.

Actually they make a sense, it tells that the value is a literal string. So we can distinguish `Foo` as interface/type and `"Foo"` as literal string.

<img width="197" alt="image" src="https://user-images.githubusercontent.com/3911343/208648295-b15823bb-ea4d-4e58-8b55-4e7c01af7479.png">

**Comment by farnabaz** [comment]
I see, so I'm closing this.
